# Generated by Django 4.2.30 on 2026-05-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('user_types', models.JSONField(blank=True, null=True)),
                ('insurance_companies', models.JSONField(blank=True, null=True)),
                ('experience_range', models.CharField(blank=True, max_length=50, null=True)),
                ('client_base', models.CharField(blank=True, max_length=50, null=True)),
                ('achievement_photo_limit', models.IntegerField(blank=True, null=True)),
                ('registration_step', models.IntegerField(default=0)),
                ('status', models.CharField(default='incomplete', max_length=50)),
                ('registration_draft', models.JSONField(blank=True, null=True)),
                ('badge', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_type', models.CharField(blank=True, max_length=50, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('upgrade_discount_percent', models.FloatField(default=0)),
                ('referred_by_code', models.CharField(blank=True, max_length=100, null=True)),
                ('referral_reward_type', models.CharField(blank=True, max_length=100, null=True)),
                ('referral_reward_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentAchievementPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_achievement_photos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentCareerTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('event_text', models.TextField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_career_timelines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_device_tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentFamilyLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('license_number', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_family_licenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentInsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'agent_insurance_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentInsuranceSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_insurance_segments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('customer_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('interaction_type', models.CharField(blank=True, max_length=50, null=True)),
                ('lead_status', models.CharField(default='new', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_leads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentLeadPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leads_new_business', models.BooleanField(default=False)),
                ('leads_portfolio_analysis', models.BooleanField(default=False)),
                ('portfolio_charging', models.CharField(blank=True, max_length=50, null=True)),
                ('portfolio_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leads_claims_support', models.BooleanField(default=False)),
                ('claims_charging', models.CharField(blank=True, max_length=50, null=True)),
                ('claims_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('claims_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_lead_preferences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentPerformanceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claims_processed', models.IntegerField(default=0)),
                ('claims_settled', models.IntegerField(default=0)),
                ('claims_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('response_time', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_performance_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(max_length=100)),
                ('primary_companies', models.JSONField(blank=True, null=True)),
                ('secondary_companies', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_portfolios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentProductExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('expertise_level', models.IntegerField(default=0)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_product_expertise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_photo_path', models.TextField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('languages', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('license_number', models.CharField(blank=True, max_length=255, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('agency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('service_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('has_pos_license', models.BooleanField(default=False)),
                ('software_name', models.CharField(blank=True, max_length=255, null=True)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('career_highlights', models.TextField(blank=True, null=True)),
                ('portfolio_breakdown', models.JSONField(blank=True, null=True)),
                ('desired_services', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateField()),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_profile_views',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewer_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('reviewer_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('review', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentServiceableCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'agent_serviceable_cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_plan', models.CharField(blank=True, max_length=255, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=50)),
                ('status', models.CharField(default='inactive', max_length=50)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_subscriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentUserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'agent_user_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'insurance_companies',
                'managed': False,
            },
        ),
    ]
